In [1]:
from __future__ import division
import numpy as np
import itertools as it

# HMM  HW #
    Problem $1$


In [2]:
#this is for problem 1:
#part a: calculate P(O|lam)
A = np.array([[0.7,0.3],[0.4,0.6]]).T
B = np.array([[0.1,0.4,0.5],[0.7,0.2,0.1]]).T
pi = np.array([0.0,1.0]).T
lam = np.array([A,B,pi])

obs = np.array([1,0,2])

def P_O_lam(A,B,pi, observations):
    T = len(observations)
    N = np.shape(A)[0] #this is the number of rows in A
    tot = 0 #running total probability...will be updated
    output = []
    
    for i in it.product(xrange(N), repeat = T):
        P = pi[i[0]]*B[observations[0],i[0]]
        
        for j in xrange(1, T):
            P *= A[i[j], i[j - 1]] * B[observations[j], i[j]]
        tot += P
        output.append((i, P))
        
    return output, tot
part_a = P_O_lam(A,B,pi,obs)
print "this is the output: \n", part_a, "\n this is the total probability:\n", part_a[1]
    
print "\n we now compute the alpha pass, this is part b \n"

def alpha_pass(A,B,pi,observations, return_all = False):
    if return_all:
        alpha_list = []
    for t in xrange(len(observations)):
        j = int(observations[t])
       
        if t == 0:
            alpha = pi * B[j, :]
        else:
            alpha = A.dot(alpha) * B[j, :]
            
        if return_all:
            alpha_list.append(alpha)
        
    if return_all:
        return alpha, alpha_list
    else:
        return alpha
print "this is my alpha pass:\n",alpha_pass(A,B,pi,obs, return_all = True)


    

this is the output: 
([((0, 0, 0), 0.0), ((0, 0, 1), 0.0), ((0, 1, 0), 0.0), ((0, 1, 1), 0.0), ((1, 0, 0), 0.0028000000000000004), ((1, 0, 1), 0.00024000000000000006), ((1, 1, 0), 0.016800000000000002), ((1, 1, 1), 0.0050400000000000002)], 0.024880000000000003) 
 this is the total probability:
0.02488

 we now compute the alpha pass, this is part b 

this is my alpha pass:
(array([ 0.0196 ,  0.00528]), [array([ 0. ,  0.2]), array([ 0.008,  0.084]), array([ 0.0196 ,  0.00528])])


This is part c:

the results simply say that this is the probability for observing that particular sequence. We use the model specified in the problem, and the algorithm described in the notes. Our results both give aboout a $20$% chance for observing the sequence: (M,S,L) given the starting model.

   part a is the direct computation

   part b uses the alpha pass computation

this is part d:

   Work factor for part a: $2T(N^T)$ multiplications are needed

   Work factor for part b: $(N^2)T$ multiplications are needed...this way is much faster


This is for problem $2$ 

part a:
    we see the output for problem 1a and pick the sequence with the highest probability:
    $P(O,X = CCH) = 0.01682$ 
    
part b:
    determining the best hidden state sequence  given the observation (M,S,L) is the state that yeilds
    the highest probability. this state is given by: Cold, Cold, Hot
    
    
    
This is for problem $3$    

In [3]:
#code for problem3a
# find P(O = (O1,O2,O3,O4)) where Oi is in (0,1,2) and verify that they sum to 1
def prob3a(A,B,pi,obs):
    total = 0
    for i in it.product(xrange(3), repeat = 4):
        Probabilities = P_O_lam(A,B,pi, i)
        print "probabilities of " + str(i) + ": "
        total += Probabilities[1]
        print Probabilities[1]
    print "this is the total: \n", total #it totally sums to one
    
prob3a(A,B,pi,obs)


probabilities of (0, 0, 0, 0): 
0.0633472
probabilities of (0, 0, 0, 1): 
0.0408856
probabilities of (0, 0, 0, 2): 
0.0388472
probabilities of (0, 0, 1, 0): 
0.032368
probabilities of (0, 0, 1, 1): 
0.029008
probabilities of (0, 0, 1, 2): 
0.030464
probabilities of (0, 0, 2, 0): 
0.0277088
probabilities of (0, 0, 2, 1): 
0.0284984
probabilities of (0, 0, 2, 2): 
0.0308728
probabilities of (0, 1, 0, 0): 
0.030184
probabilities of (0, 1, 0, 1): 
0.020272
probabilities of (0, 1, 0, 2): 
0.019544
probabilities of (0, 1, 1, 0): 
0.020272
probabilities of (0, 1, 1, 1): 
0.019936
probabilities of (0, 1, 1, 2): 
0.021392
probabilities of (0, 1, 2, 0): 
0.019544
probabilities of (0, 1, 2, 1): 
0.021392
probabilities of (0, 1, 2, 2): 
0.023464
probabilities of (0, 2, 0, 0): 
0.0248528
probabilities of (0, 2, 0, 1): 
0.0170744
probabilities of (0, 2, 0, 2): 
0.0165928
probabilities of (0, 2, 1, 0): 
0.01904
probabilities of (0, 2, 1, 1): 
0.019376
probabilities of (0, 2, 1, 2): 
0.020944
probabil

In [4]:
def prob3b(A, B, pi, obs):
    Probabilities = np.zeros(81)
    count = 0
    
    for i in it.product(xrange(3), repeat = 4):
        alpha, alpha_list = alpha_pass(A, B, pi, i, return_all = True)
        Probabilities[count] = alpha_list[-1].sum()
        count += 1
    return Probabilities, np.sum(Probabilities)
print "these are the probabilities for problem 3b...done with an alpha pass:\n"
print prob3b(A,B,pi,obs)[0], "\n and this is their total sum: \n", prob3b(A,B,pi,obs)[1] #sums to 1!!!

these are the probabilities for problem 3b...done with an alpha pass:

[ 0.0633472  0.0408856  0.0388472  0.032368   0.029008   0.030464
  0.0277088  0.0284984  0.0308728  0.030184   0.020272   0.019544   0.020272
  0.019936   0.021392   0.019544   0.021392   0.023464   0.0248528
  0.0170744  0.0165928  0.01904    0.019376   0.020944   0.0191632
  0.0213976  0.0235592  0.0180992  0.0116816  0.0110992  0.009248   0.008288
  0.008704   0.0079168  0.0081424  0.0088208  0.008624   0.005792   0.005584
  0.005792   0.005696   0.006112   0.005584   0.006112   0.006704
  0.0071008  0.0048784  0.0047408  0.00544    0.005536   0.005984
  0.0054752  0.0061136  0.0067312  0.0090496  0.0058408  0.0055496
  0.004624   0.004144   0.004352   0.0039584  0.0040712  0.0044104
  0.004312   0.002896   0.002792   0.002896   0.002848   0.003056   0.002792
  0.003056   0.003352   0.0035504  0.0024392  0.0023704  0.00272    0.002768
  0.002992   0.0027376  0.0030568  0.0033656] 
 and this is their total sum: 


This is for problem $4$

write the re-estimation formulae 9,10,11 in terms of $\alpha$, and $beta$

For $i = 0, 1, ... , N - 1$ and $j = 0, 1, ... , N - 1$ and $k = 0, 1 , ... , N-1$  and $\pi_i = \gamma_0(i)$


$(9)$




$\pi_i = \alpha_0(i)\beta_0(i) / P(O|X)$

$(10)$



$a_{ij} = \sum\limits_{t=0}^{T-2} \gamma_t(i, j) / \sum\limits_{t=0}^{T-2} \gamma_t(i)$

$\implies a_{ij} = \sum\limits_{t=0}^{T-2} \alpha_t(i)a_{ij}b_j(O_{t+1})\beta_{t+1}(j) / \sum\limits_{t=0}^{T-2}\alpha_0(i)\beta_0(i) / P(O|X)$

$\implies  a_{ij} = \sum\limits_{t=0}^{T-2} \alpha_t(i)a_{ij}b_j(O_{t+1})\beta_{t+1}(j) / \sum\limits_{t=0}^{T-2} \alpha_t(i)\beta_t(i)$

$(11)$



$b_j(k) = \sum\nolimits_{t \in 0, 1, ..., T-1; O_t = k} \gamma_t(i) / \sum\limits_{t=0}^{T-1} \gamma_t(i)$

$\implies b_j(k) = \sum\nolimits_{t \in 0, 1, ..., T-1; O_t = k} \alpha_t(i)\beta_t(i) / P(O |X) / \sum\limits_{t=0}^{T-1} \alpha_t(i)\beta_t(i) / P(O|X)$

$\implies b_j(k) = \sum\nolimits_{t \in 0, 1, ..., T-1; O_t = k} \alpha_t(i)\beta_t(i) / \sum\limits_{t=0}^{T-1} \alpha_t(i)\beta_t(i)$

This is for problem $9$


In [5]:
#in order to scale things I'll need a beta pass:
def beta_pass(A, B, pi, Ob, return_all = False):
    if return_all:
        beta_list = []
        
    for t in xrange(len(Ob)):
        j = int(Ob[-t])
        
        if t == 0:
            beta = np.ones_like(pi)
        else:
            beta = A.T.dot(beta * B[j, :])
            
        if return_all:
            beta_list.append(beta)
    
    if return_all:
        return beta, beta_list
    else:
        return beta
    
    
def scale_alpha(A, B, pi, Ob):
    T = len(Ob)
    N = len(pi)
    c = np.zeros(T)

    alpha = np.zeros((T, N))
    alpha[0]  = pi * B[Ob[0]]
    c[0] = 1. / alpha[0].sum()
    alpha[0] *= c[0]

    for t in xrange(1, T):
        alpha[t] = np.dot(A.T, alpha[t - 1]) * B[Ob[t]]
        c[t] = 1. / alpha[t].sum()
        alpha[t] *= c[t]

    return alpha, c #we want to return C because it will be used in the beta scaling

def scale_beta(A, B, pi, Ob, c):
    T = len(Ob)
    N = len(pi)
    d = c

    beta = np.zeros((T, N))
    beta[-1] = np.ones(N)
    d[-1] = 1. / beta[-1].sum()
    beta[-1] *= d[-1]

    for t in range(0, T - 1)[::-1]:
        beta[t] = np.dot(A.T, beta[t + 1] * B[Ob[t + 1]])
        d[t] = 1. / beta[t].sum()
        beta[t] *= d[t]

    return beta

def stoch(S, M):
    A = np.random.rand(S, S)
    A /= np.hstack(A.sum(axis = 0))
    
    B = np.random.rand(M, S)
    B /= np.hstack(B.sum(axis = 0))

    pi = np.random.rand(S)
    pi /= pi.sum()

    return A, B, pi

def clean(datafile):
    f = open(datafile)
    data = f.read()[:50000]
    Ob = list(data)
    T = len(Ob)
    i = 0

    while i != T:
        pos = ord(Ob[i])
        if pos == 32:
            Ob[i] = 0

        elif pos >= 65 and pos <= 90:
            Ob[i] = pos - 64

        elif pos >= 97 and pos <= 122:
            Ob[i] = pos - 96

        else:
            del Ob[i]
            T -= 1
            i -= 1
        i += 1
    return Ob, T


def prob9(datafile, S, maxiters = 10):
    M = 27
    iters = 0
    O, T = clean(datafile)
    A,B,pi = stoch(S,M)
    logprob = -np.inf
    oldLogProb = -np.inf
    diff = 1
    while(iters < maxiters and diff > 0): #this keeps updating our model
        alpha, c = scale_alpha(A,B,pi,O)
        beta = scale_beta(A,B,pi,O,c)

        dig = np.zeros((T,S,S))
        gamma = np.zeros((T,S))
        for t in xrange(T-1):
            for i in xrange(S):
                for j in xrange(S):
                    dig[t,i,j] = alpha[t,i]*A[j,i]*B[O[t+1],j]*beta[t+1,j]
            dig[t] = dig[t]/dig[t].sum()

        gamma = dig.sum(axis =1)
        pi = gamma[0]
        for i in range(S):
            for j in range(S):
                A[i,j] = dig[:,i,j].sum()/gamma[:,i].sum()
        for i in range(S):
            for j in range(M):
                numer = 0
                for t in range(T):
                    if O[t] == j : numer += gamma[t,i]
                denom = gamma[:,i].sum()
                B[j,i] = numer/denom
        oldLogProb = logprob

        logprob = -c.sum()
        dif = logprob*oldLogProb
        iters +=1
    return pi, A, B.argmax(axis=1)

datafile = 'brown.txt'
print prob9(datafile,2,10)

print "trying to do it with 3 states\n"
print prob9(datafile,3,10)

print "trying to do it with 4 states\n"
print prob9(datafile,4,10)

(array([ 0.81617882,  0.18382118]), array([[ 0.99617792,  0.22361399],
       [ 0.0169704 ,  0.00713277]]), array([0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1], dtype=int64))
trying to do it with 3 states

(array([ 0.00205054,  0.08240492,  0.91554454]), array([[  9.99989351e-01,   3.77949579e+01,   4.23447316e+02],
       [  2.81752823e-07,   1.49343482e-06,   2.03507898e-06],
       [  6.35695852e-14,   2.60223820e-13,   2.16910592e-12]]), array([1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0], dtype=int64))
trying to do it with 4 states

(array([  3.91343274e-01,   6.43949375e-07,   6.08625018e-01,
         3.10636272e-05]), array([[  9.74161410e-01,   1.44205100e-06,   1.56233214e+00,
          7.60265170e-05],
       [  1.57078582e+04,   1.22865830e-01,   1.57977423e+04,
          1.97351897e+00],
       [  3.95988067e-07,   2.61006018e-12,   1.17403300e-08,
          7.60672460e-11],
       [  1.21

The explanation of how this algorithm works is best found in the pseudocode for the notes, but
I think what makes most sense to me is the overall process. We're trying to find a model (A,B, pi)
that will most likely give us our state.


So we first initialize our model

$\lambda$ = (A,B,pi)

Then we compute our $\alpha(i)$, $\beta(i)$, $\gamma(i,j)$, $\gamma(i)$

then we use those values to update our model $\lambda$ = (A_updated,B_updated,pi)

we repeat the process as long as our probability increases, or until a stopping point


$problem 10$ 

part a, I've had some struggles making it work, but this was my best effort

In [6]:
#problem 10a, uses the same algorith as problem 9, but with a different data set aka. the cypher text
data ='ciphertext.txt'
print prob9(data,2,10)

(array([ 0.54790599,  0.45209401]), array([[  5.44361682e-14,   1.92749826e-14],
       [  1.21197591e+00,   1.00000000e+00]]), array([1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1], dtype=int64))
